export { default as Login } from './login';
export { default as Signup } from './signup';
export { default as Dashboard } from './dashboard';
export { default as Staff } from './staff';
export { default as Parent } from './parent';
export { default as Student } from './student';
export { default as ViewStaff } from './view-staff';
export { default as ViewStudent } from './view-student';
export { default as ViewParent } from './view-parent';
