export const QUERY_STALE_TIME = 1000 * 60 * 5; // 5 minutes;

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_STAFF_LIST = 'FETCH_STAFF_LIST';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_PARENT_LIST = 'FETCH_PARENT_LIST';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const FETCH_CLASS_ARMS = 'FETCH_CLASS_ARMS';
export const FETCH_SCHOOL_CLASS = 'FETCH_SCHOOL_CLASS';
export const FETCH_GENERAL_CLASS_LIST = 'FETCH_GENERAL_CLASS_LIST';
